#ifndef INFINITE_TEXTURE_PY_RPC_ACK_DECODER_H
#define INFINITE_TEXTURE_PY_RPC_ACK_DECODER_H

#include <cstdint>
#include <string>
#include <string_view>

namespace build_import {

inline constexpr uint32_t kPyRpcPacketId = 0xC8U;
inline constexpr uint32_t kPyRpcClientMessageId = 9753608U;
inline constexpr std::string_view kBuildImportRpcUuidPrefix = "infinitecz_build_";
inline constexpr char kBuildImportSilentRpcUuid[] = "infinitecz_build_silent";
inline constexpr std::string_view kBuildExportTeleportProbeUuidPrefix =
    "infinitecz_export_tp_probe_";

inline bool isBuildImportRpcUuid(std::string_view uuid) {
    return uuid.size() >= kBuildImportRpcUuidPrefix.size() &&
           uuid.substr(0, kBuildImportRpcUuidPrefix.size()) == kBuildImportRpcUuidPrefix;
}

inline bool isBuildExportTeleportProbeUuid(std::string_view uuid) {
    return uuid.size() >= kBuildExportTeleportProbeUuidPrefix.size() &&
           uuid.substr(0, kBuildExportTeleportProbeUuidPrefix.size()) ==
               kBuildExportTeleportProbeUuidPrefix;
}

enum class PyRpcAckEventKind : uint8_t {
    None = 0,
    AfterExecuteCommand,
    ExecuteCommandOutput,
    AvailableCheckFailed,
};

struct PyRpcAckEvent {
    PyRpcAckEventKind kind = PyRpcAckEventKind::None;
    std::string uuid;
    bool execute_result = false;
    std::string reason;
};

inline bool shouldSuppressBuildImportRpcFeedback(const PyRpcAckEvent& event,
                                                 bool importer_active) {
    if (event.kind == PyRpcAckEventKind::AfterExecuteCommand ||
        event.kind == PyRpcAckEventKind::ExecuteCommandOutput) {
        return isBuildImportRpcUuid(event.uuid);
    }
    return event.kind == PyRpcAckEventKind::AvailableCheckFailed && importer_active;
}

// Decodes a complete Bedrock PyRpc packet. Unrelated, malformed, oversized,
// or unsupported packets return false and leave event reset to its default.
bool decodePyRpcAckPacket(std::string_view packet, PyRpcAckEvent* event);

// Allocation-free fast path for the per-command feedback generated by
// untracked importer commands. The complete PyRpc envelope and MessagePack
// event shape are validated before a packet is classified as suppressible.
bool isSilentBuildImportRpcPacket(std::string_view packet);

}  // namespace build_import

#endif  // INFINITE_TEXTURE_PY_RPC_ACK_DECODER_H
