#ifndef INFINITE_TEXTURE_PY_RPC_ENVELOPE_BRIDGE_H
#define INFINITE_TEXTURE_PY_RPC_ENVELOPE_BRIDGE_H

namespace build_import {

// The target Python runtime serializes tuples through a custom msgpack
// default hook. A calibrated byte template keeps every fixed envelope byte,
// including playerId, and replaces only the cmd/uuid scalar encodings. The
// first command in every MessagePack string-width class is compared against
// the legacy packer byte-for-byte. Any type, ordering, or codec mismatch
// permanently falls back to the legacy implementation.
inline const char* rpcReusableEnvelopePythonSource() {
    return
        "try:\n"
        "  _build_import_rpc_text_type = unicode\n"
        "except NameError:\n"
        "  _build_import_rpc_text_type = str\n"
        "_build_import_rpc_binary_type = str if sys.version_info[0] < 3 else bytes\n"
        "_build_import_rpc_template_state = [None]\n"
        "def _build_import_rpc_pack_legacy(player_id, cmd, command_uuid, _pack=_build_import_rpc_pack):\n"
        "  return _pack(('ModEventC2S', ('Minecraft', 'aiCommand', 'ExecuteCommandEvent', {'playerId': player_id, 'cmd': cmd, 'uuid': command_uuid, 'aiModel': '-1'}), None))\n"
        "def _build_import_rpc_pack_string(value, _text=_build_import_rpc_text_type, _binary=_build_import_rpc_binary_type, _struct=struct):\n"
        "  is_text = isinstance(value, _text) and not isinstance(value, _binary)\n"
        "  if is_text:\n"
        "    raw = value.encode('utf-8')\n"
        "    size = len(raw)\n"
        "    if size <= 31:\n"
        "      return (_struct.pack('>B', 160 | size) + raw, 0)\n"
        "    if size <= 255:\n"
        "      return (_struct.pack('>BB', 217, size) + raw, 1)\n"
        "    if size <= 65535:\n"
        "      return (_struct.pack('>BH', 218, size) + raw, 2)\n"
        "    if size <= 4294967295:\n"
        "      return (_struct.pack('>BI', 219, size) + raw, 3)\n"
        "    return None\n"
        "  if not isinstance(value, _binary):\n"
        "    return None\n"
        "  raw = value\n"
        "  size = len(raw)\n"
        "  if size <= 255:\n"
        "    return (_struct.pack('>BB', 196, size) + raw, 4)\n"
        "  if size <= 65535:\n"
        "    return (_struct.pack('>BH', 197, size) + raw, 5)\n"
        "  if size <= 4294967295:\n"
        "    return (_struct.pack('>BI', 198, size) + raw, 6)\n"
        "  return None\n"
        "def _build_import_rpc_marker(value, text_marker, binary_marker, _text=_build_import_rpc_text_type, _binary=_build_import_rpc_binary_type):\n"
        "  if isinstance(value, _text) and not isinstance(value, _binary):\n"
        "    return text_marker\n"
        "  if isinstance(value, _binary):\n"
        "    return binary_marker\n"
        "  return None\n"
        "def _build_import_rpc_make_template(player_id, cmd, command_uuid, _legacy=_build_import_rpc_pack_legacy, _pack_string=_build_import_rpc_pack_string, _marker=_build_import_rpc_marker):\n"
        "  cmd_marker = _marker(cmd, u'infinitecz_cmd_template_marker', b'infinitecz_cmd_template_marker')\n"
        "  uuid_marker = _marker(command_uuid, u'infinitecz_uuid_template_marker', b'infinitecz_uuid_template_marker')\n"
        "  if cmd_marker is None or uuid_marker is None:\n"
        "    return None\n"
        "  cmd_token = _pack_string(cmd_marker)\n"
        "  uuid_token = _pack_string(uuid_marker)\n"
        "  if cmd_token is None or uuid_token is None:\n"
        "    return None\n"
        "  cmd_token = cmd_token[0]\n"
        "  uuid_token = uuid_token[0]\n"
        "  probe = _legacy(player_id, cmd_marker, uuid_marker)\n"
        "  if probe.count(cmd_token) != 1 or probe.count(uuid_token) != 1:\n"
        "    return None\n"
        "  cmd_at = probe.find(cmd_token)\n"
        "  uuid_at = probe.find(uuid_token)\n"
        "  if cmd_at < uuid_at:\n"
        "    return [player_id, 0, probe[:cmd_at], probe[cmd_at + len(cmd_token):uuid_at], probe[uuid_at + len(uuid_token):], {}, None, None]\n"
        "  return [player_id, 1, probe[:uuid_at], probe[uuid_at + len(uuid_token):cmd_at], probe[cmd_at + len(cmd_token):], {}, None, None]\n"
        "def _build_import_rpc_pack_event(player_id, cmd, command_uuid, _legacy=_build_import_rpc_pack_legacy, _pack_string=_build_import_rpc_pack_string, _make_template=_build_import_rpc_make_template, _state=_build_import_rpc_template_state):\n"
        "  state = _state[0]\n"
        "  if state is False:\n"
        "    return _legacy(player_id, cmd, command_uuid)\n"
        "  try:\n"
        "    if state is None or type(state[0]) is not type(player_id) or state[0] != player_id:\n"
        "      state = _make_template(player_id, cmd, command_uuid)\n"
        "      if state is None:\n"
        "        _state[0] = False\n"
        "        return _legacy(player_id, cmd, command_uuid)\n"
        "      _state[0] = state\n"
        "    packed_cmd = _pack_string(cmd)\n"
        "    if state[6] is not None and type(state[6]) is type(command_uuid) and state[6] == command_uuid:\n"
        "      packed_uuid = state[7]\n"
        "    else:\n"
        "      packed_uuid = _pack_string(command_uuid)\n"
        "      state[6] = command_uuid\n"
        "      state[7] = packed_uuid\n"
        "    if packed_cmd is None or packed_uuid is None:\n"
        "      return _legacy(player_id, cmd, command_uuid)\n"
        "    if state[1] == 0:\n"
        "      optimized = state[2] + packed_cmd[0] + state[3] + packed_uuid[0] + state[4]\n"
        "    else:\n"
        "      optimized = state[2] + packed_uuid[0] + state[3] + packed_cmd[0] + state[4]\n"
        "    signature = (packed_cmd[1], packed_uuid[1])\n"
        "    if signature not in state[5]:\n"
        "      legacy = _legacy(player_id, cmd, command_uuid)\n"
        "      if optimized != legacy:\n"
        "        _state[0] = False\n"
        "        return legacy\n"
        "      state[5][signature] = 1\n"
        "    return optimized\n"
        "  except BaseException:\n"
        "    _state[0] = False\n"
        "    return _legacy(player_id, cmd, command_uuid)\n";
}

}  // namespace build_import

#endif  // INFINITE_TEXTURE_PY_RPC_ENVELOPE_BRIDGE_H
