if(NOT DEFINED SOURCE_FILE)
    message(FATAL_ERROR "SOURCE_FILE is required")
endif()

file(READ "${SOURCE_FILE}" runtime_source)
set(select_marker "if (stage_ == ExecuteStage::MapSelect) {")
set(settle_marker "if (stage_ == ExecuteStage::MapSettle) {")
string(FIND "${runtime_source}" "${select_marker}" select_start)
string(FIND "${runtime_source}" "${settle_marker}" settle_start)
if(select_start EQUAL -1 OR settle_start LESS_EQUAL select_start)
    message(FATAL_ERROR "Cannot isolate map selection and supply flow")
endif()
math(EXPR select_length "${settle_start} - ${select_start}")
string(SUBSTRING "${runtime_source}" ${select_start} ${select_length} select_source)

set(readback_marker "if (empty_count > supply.empty_maps_before) {")
set(ack_marker "if (!map_blank_supply_ack_received_ && now >= map_blank_supply_poll_at_) {")
set(timeout_marker "if (now >= map_blank_supply_deadline_) {")
set(arm_marker "if (!ArmMapBlankSupply(map_state_path_, supply, &supply_error)) {")
set(give_marker "\"/give @s minecraft:empty_map 1\"")
foreach(marker IN ITEMS readback_marker ack_marker timeout_marker arm_marker give_marker)
    string(FIND "${select_source}" "${${marker}}" marker_position)
    if(marker_position EQUAL -1)
        message(FATAL_ERROR "Map blank supply flow is missing ${marker}")
    endif()
    set(${marker}_position ${marker_position})
endforeach()
if(NOT readback_marker_position LESS ack_marker_position OR
   NOT ack_marker_position LESS timeout_marker_position OR
   NOT arm_marker_position LESS give_marker_position)
    message(FATAL_ERROR "Map blank supply readback, ACK, timeout or durable arm is reordered")
endif()

math(EXPR ack_length "${timeout_marker_position} - ${ack_marker_position}")
string(SUBSTRING "${select_source}" ${ack_marker_position} ${ack_length} ack_source)
foreach(required IN ITEMS "RpcResultState::Rejected" "map_blank_supply_ack_received_ = true;")
    string(FIND "${ack_source}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Map supply ACK handling is missing ${required}")
    endif()
endforeach()
foreach(forbidden IN ITEMS "ClearMapBlankSupply(" "pauseMapCreation(" "executeTrackedCommands(")
    string(FIND "${ack_source}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Map supply ACK branch must not clear intent, pause, or resend")
    endif()
endforeach()

string(SUBSTRING "${select_source}" ${timeout_marker_position} -1 timeout_source)
string(FIND "${timeout_source}" "the durable intent prevents an automatic duplicate give"
       duplicate_guard_position)
if(duplicate_guard_position EQUAL -1)
    message(FATAL_ERROR "Map supply timeout lost its no-resend diagnostic")
endif()
